# Generated by Django 4.2.3 on 2023-11-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_addcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('semail', models.EmailField(max_length=100)),
                ('smobile', models.CharField(max_length=100)),
                ('saddress', models.CharField(max_length=100)),
                ('scollege', models.CharField(max_length=100)),
                ('sdegree', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('sdue_amount', models.IntegerField()),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.addcourse')),
            ],
        ),
    ]
