# Generated by Django 4.2.3 on 2023-11-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_addstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='sdue_amount',
            new_name='due_amount',
        ),
    ]
